apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  nodeSelector:
    "beta.kubernetes.io/os": linux
  containers:
  - image: monubamb-microsoft.azurecr.io/nginx:1.0
    name: nginx
    ports:
    - containerPort: 80
 
