name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      registry:
        description: Docker registry
        default: ghcr.io
        required: false
        type: string

      username:
        description: Docker registry username
        default: ${{ github.actor }}
        required: false
        type: string

      dockerfile:
        description: Dockerfile path
        default: ./Dockerfile
        required: false
        type: string
    
    secrets:
      password:
        description: Dockerfile registry password
        required: false 

env:
  DOCKER_IMAGE: ${{ inputs.registry }}/${{ github.repository }}
  DOCKER_PASSWORD: ${{ secrets.password || secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker image
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max
